name: Update data
on:
  schedule:
    - cron:  '0 15 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          pip install csv-diff
      - name: Copy old version
        run: cp data/paris-agreement-entry-into-force.csv data/paris-agreement-entry-into-force-old.csv
      - name: Update data
        run: python scripts/process.py
      - name: Diff files
        run: csv-diff data/paris-agreement-entry-into-force-old.csv data/paris-agreement-entry-into-force.csv --key=Code --singular=party --plural=parties >> message.txt
      - name: Commit back
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "<>"
          git config user.name "Update Bot"
          git checkout main
          git add data/paris-agreement-entry-into-force.csv
          git commit -F message.txt && \
            git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git main || true
          git log -n 2

